### PR TITLE
Make password constraints consistent.

### LINKED ISSUE #430: Password constraints are not obvious
Using TypeMill 2.0.3, I started setting things up locally. I used my password manager to generate a password:

typemill-setup-admin

Then I was taken to `/tm/login` and asked to login. I tried, but got a **Wrong password or username** error:

typemill-login

I was a little confused, and spun my wheels trying to figure this out a little. The problem seemed to be because when the [inputs are validated](https://github.com/typemill/typemill/blob/648d70448b7f14c6a35a1a7d765922082d489f0c/system/typemill/Controllers/ControllerWebAuth.php#L37) it is enforcing a rule that passwords [must be between 5 - 20 characters in length](https://github.com/typemill/typemill/blob/648d70448b7f14c6a35a1a7d765922082d489f0c/system/typemill/Models/Validation.php#L266).

20 characters seems like quite a low limit—it is definitely below the password defaults I set up in my password manager—but ignoring that: there is no feedback to make it clear that this expectation was not met. It feels like this feedback should be given during the setup stage, before the new admin account is created.

### PR DESCRIPTION
**Pull request by barryhughes**
To avoid confusion, we should probably use the same min and max character lengths for passwords during sign-up and sign-in.

In this case, it felt like the sign-in rules should be made consistent with the sign-up rules (they allow for passwords up to 40 chars in length, which is a little nicer).

Closes https://github.com/typemill/typemill/issues/430

### CODE REVIEW

File: system/typemill/Models/Validation.php [hunk 1]
```diff
@@ -888,4 +888,4 @@ public function recursiveValidation(array $formdefinitions, $input, $output = []
 
 		return $output;
 	}
-}
\ No newline at end of file
+}
```
Comment (barryhughes) [inline system/typemill/Models/Validation.php:891]:
```suggestion
}

```

**Comment by trendschau** [comment]
great find, thank you!
